bot:
#  name: LigaNNGitLabBot
#  token: 6016141424:AAGsG-Z32bMvE5pXve8cslGnjR5VWLEGyao
#  test
  name: bnnligalabgit_test_bot
  token: 6308490047:AAGbBo8c8Bniz5P0uXKY0YNqQ-lACPi6SjI
logging:
  level:
    org.boris.bot: DEBUG
spring:
  datasource:
    driverClassName: org.h2.Driver
    username: boot
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
flyway:
  user: boot
  password:
  schema: boot-schema
  locations: filesystem:db/migration