server:
  port: 9000
  servlet:
    context-path: /liga-bot
bot:
#  name: NNLigaGitLabBot v1
  name: NNLigaGitLabBotV1.1
#  token: 6055621978:AAEP9bk-LDPR6e_nBaEsj-5fXrpO6Dt7DrY v1
  token: 6664963618:AAGkovLflYCYUMXTCv6N9gVRQABwyKKs31k
logging:
  level:
    ru.git.lab.bot: DEBUG
spring:
  datasource:
    driverClassName: org.h2.Driver
    username: bot
    password:
#    url: jdbc:h2:file:~\\bot\\data\\bot-db
    url: jdbc:h2:file:~\\bot-1.1\\data\\bot-db
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    user: bot
    password:
    schema: bot-schema
    locations: classpath:db/migration
#    url: jdbc:h2:file:~\\bot\\data\\bot-db
    url: jdbc:h2:file:~\\bot-1.1\\data\\bot-db
