bot:
  name: LigaNNGitLabBot
  token: 6016141424:AAGsG-Z32bMvE5pXve8cslGnjR5VWLEGyao
logging:
  level:
    ru.git.lab.bot: DEBUG
spring:
  datasource:
    driverClassName: org.h2.Driver
    username: bot
    password:
    url: jdbc:h2:file:~\\boot\\data\\boot-db
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
flyway:
  user: bot
  password:
  schema: bot-schema
  locations: filesystem:db/migration
  url: jdbc:h2:file:~\\boot\\data\\boot-db
