bot:
  name: LigaNNGitLabBot
  token: 6016141424:AAGsG-Z32bMvE5pXve8cslGnjR5VWLEGyao
logging:
  level:
    org.boris.bot: DEBUG
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./data/boot
    username: boot
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
flyway:
  user: boot
  password:
  schema: boot-schema
  url: jdbc:h2:file:./data/boot
  locations: filesystem:db/migration