bot:
  name: LigaNNGitLabBot
  token: 6016141424:AAGsG-Z32bMvE5pXve8cslGnjR5VWLEGyao
logging:
  level:
    org.boris.bot: DEBUG
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:boot-db;
    username: boot
    password: 0000
    h2:
      console:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
flyway:
  user: boot
  password: 0000
  schemas: boot-db
  url: jdbc:h2:mem:boot-db
  locations: filesystem:db/migration